# Generated by Django 5.2.6 on 2025-12-20 12:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CombinedRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(max_length=100)),
                ("customer", models.CharField(max_length=200)),
                ("customer_address", models.TextField(blank=True)),
                ("date_np", models.CharField(blank=True, max_length=50)),
                ("product_name", models.CharField(max_length=200)),
                ("quantity", models.IntegerField()),
                ("rate", models.FloatField()),
                ("total", models.FloatField()),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("customer", models.CharField(max_length=200)),
                ("customer_address", models.TextField(blank=True)),
                ("total", models.FloatField(default=0)),
                ("status", models.CharField(default="Pending", max_length=50)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("date_np", models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("price", models.FloatField(default=0.0)),
                ("description", models.TextField(blank=True)),
                ("stock", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("particulars", models.CharField(max_length=200)),
                ("quantity", models.IntegerField(default=1)),
                ("rate", models.FloatField()),
                ("amount", models.FloatField(blank=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="api.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.product"
                    ),
                ),
            ],
        ),
    ]
