# Generated by Django 5.0.1 on 2025-12-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerecord',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
