# Generated by Django 6.0 on 2025-12-10 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_salerecord_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="salerecord",
            options={"ordering": ["-date"]},
        ),
        migrations.AddField(
            model_name="order",
            name="customer_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="order",
            name="date_np",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="salerecord",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sale_records",
                to="api.order",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total",
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("particulars", models.CharField(max_length=200)),
                ("quantity", models.IntegerField(default=1)),
                ("rate", models.FloatField()),
                ("amount", models.FloatField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="api.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.product"
                    ),
                ),
            ],
        ),
    ]
